### PR TITLE
Added Inform 7 version

### PR DESCRIPTION
**Pull request by nateProjects**
Hi Taciano, I've been enjoying your videos and project. 

I just thought you might find this other version interesting.

It can be run online here - https://borogove.app/ (Inform 7)

Or in the desktop app - https://ganelson.github.io/inform-website/downloads/

### CODE REVIEW

**Comment by taciano-perez** [comment]
Oh, this is so cool! Thank you so much, Nate!

It sort of goes beyond my original intent (which was using "historically relevant", in other words, ancient versions of languages that we still use), but it's too cool for me to pass the chance.

I wasn't aware of Inform, thanks for teaching me something new.

I will probably make a video out of this, if you allow. Would you like to be part of it?

**Comment by nateProjects** [comment]
Glad you like it! You are very welcome!

I thought about adding some old 8-bit formats as well as some other newer ones for the fun of it too.

I'd be happy to help with a video. I work odd shifts, but am sure we could figure out a time that worked.

**Comment by taciano-perez** [comment]
We could either record it live/interactively at a time that suits us both, or we can record separate parts and then I edit them together. Do you have a preference?
 
I imagine a structure like this:
- Video Intro
- Intro to Inform: what it is + dev environment + resources
- Step by step tutorial on how to build the "game" (I still have trouble calling something this short a game, but you get the idea)

**Comment by nateProjects** [comment]
I'm wondering what will work best. 

I like the idea of us doing it live together, but I'm pretty tied up til mid-February.

So if you want it before then maybe me sending you videos you can intro, edit comment on would work better.

Let me know if you are happy to wait, or would like me to throw a video together sooner.

**Comment by taciano-perez** [comment]
This is a hobby, so no rush.

If I start something, I will send you in private and we decide together what to do with it.

**Pull request merged**
